[env:pump_vfd]
platform = espressif32
board = esp32dev
framework = arduino

monitor_speed = 115200
upload_speed = 921600

build_flags =
  -DBUILD_GIT_HASH="b4ca847"
  -I../drukmix_bus/include
  -DCORE_DEBUG_LEVEL=0
